add erorr input

diff --git a/.github/workflows/sleep-with-concurrency-key.yaml b/.github/workflows/sleep-with-concurrency-key.yaml
--- a/.github/workflows/sleep-with-concurrency-key.yaml
+++ b/.github/workflows/sleep-with-concurrency-key.yaml
@@ -11,6 +11,11 @@ on:
         description: an identifier that will prevent equally keyed workflows from running at the same time
         type: string
         required: true
+      SHOULD_FAIL:
+        description: whether or not the workflow should fail at the end of the sleep
+        type: boolean
+        required: false
+        default: false
 
 jobs:
   sleep:
@@ -25,3 +30,7 @@ jobs:
           echo '::info::sleeping for ${{ inputs.TIME_TO_SLEEP }}s...'
           sleep ${{ inputs.TIME_TO_SLEEP }}
           echo '::info::sleep over; finishing job'
+      - if: ${{ inputs.SHOULD_FAIL == 'true' }}
+        run:
+          echo '::info::erroring workflow out as requested'
+          exit 1
diff --git a/.github/workflows/sleep.yaml b/.github/workflows/sleep.yaml
--- a/.github/workflows/sleep.yaml
+++ b/.github/workflows/sleep.yaml
@@ -11,6 +11,11 @@ on:
         description: what GitHub environment to run the job for
         type: string
         required: false
+      SHOULD_FAIL:
+        description: whether or not the workflow should fail at the end of the sleep
+        type: boolean
+        required: false
+        default: false
 
 jobs:
   sleep:
@@ -21,3 +26,7 @@ jobs:
           echo '::info::sleeping for ${{ inputs.TIME_TO_SLEEP }}s...'
           sleep ${{ inputs.TIME_TO_SLEEP }}
           echo '::info::sleep over; finishing job'
+      - if: ${{ inputs.SHOULD_FAIL == 'true' }}
+        run:
+          echo '::info::erroring workflow out as requested'
+          exit 1
